
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S4457:Parameter validation in \"async\"/\"await\" methods should be wrapped", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.AgentPoolScanFunction.Run(Microsoft.Azure.WebJobs.TimerInfo,Microsoft.Extensions.Logging.ILogger)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.AgentPoolScanFunction.Run(Microsoft.Azure.WebJobs.TimerInfo,Microsoft.Extensions.Logging.ILogger)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Completeness.Activities.GetCompletedScansFromLogAnalyticsActivity.RunAsync(Microsoft.Azure.WebJobs.DurableActivityContextBase)~System.Threading.Tasks.Task{System.Collections.Generic.List{System.String}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Completeness.Starters.CompletenessCheckStarter.RunAsync(Microsoft.Azure.WebJobs.TimerInfo,Microsoft.Azure.WebJobs.DurableOrchestrationClientBase)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.ReconcileFunction.Reconcile(System.Net.Http.HttpRequestMessage,System.String,System.String,System.String,System.String,System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.ReconcileFunction.HasPermission(System.Net.Http.HttpRequestMessage,System.String,System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.ServiceHooksSubscriptions.Run(Microsoft.Azure.WebJobs.TimerInfo)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Starters.ProjectScanHttpStarter.Run(System.Net.Http.HttpRequestMessage,System.String,System.String,System.String,Microsoft.Azure.WebJobs.DurableOrchestrationClientBase)~System.Threading.Tasks.Task{System.Net.Http.HttpResponseMessage}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Starters.ProjectsScanStarter.Run(Microsoft.Azure.WebJobs.TimerInfo,Microsoft.Azure.WebJobs.DurableOrchestrationClientBase)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.PoisonQueueFunction.Requeue(System.Net.Http.HttpRequestMessage,System.String,Microsoft.Extensions.Logging.ILogger)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.StatusFunction.Run(Microsoft.AspNetCore.Http.HttpRequest,Microsoft.Extensions.Logging.ILogger)~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Completeness.Starters.OrchestratorCleanUpStarter.RunAsync(Microsoft.Azure.WebJobs.TimerInfo,Microsoft.Azure.WebJobs.DurableOrchestrationClientBase)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Completeness.Activities.GetOrchestratorsToPurgeActivity.Run(Microsoft.Azure.WebJobs.DurableActivityContextBase,Microsoft.Azure.WebJobs.DurableOrchestrationClientBase)~System.Threading.Tasks.Task{System.Collections.Generic.IList{Microsoft.Azure.WebJobs.DurableOrchestrationStatus}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Completeness.Activities.PurgeMultipleOrchestratorsActivity.RunAsync(Microsoft.Azure.WebJobs.DurableActivityContext,Microsoft.Azure.WebJobs.DurableOrchestrationClientBase)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Completeness.Activities.PurgeMultipleOrchestratorsActivity.RunAsync(Microsoft.Azure.WebJobs.DurableActivityContextBase,Microsoft.Azure.WebJobs.DurableOrchestrationClientBase)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Completeness.Activities.GetAllOrchestratorsActivity.RunAsync(Microsoft.Azure.WebJobs.DurableActivityContextBase,Microsoft.Azure.WebJobs.DurableOrchestrationClientBase)~System.Threading.Tasks.Task{System.}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.MonitorQueueLengthsFunction.Run(Microsoft.Azure.WebJobs.TimerInfo,Microsoft.Extensions.Logging.ILogger)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Completeness.Activities.GetAllOrchestratorsActivity.RunAsync(Microsoft.Azure.WebJobs.DurableActivityContextBase,Microsoft.Azure.WebJobs.DurableOrchestrationClientBase)~System.Threading.Tasks.Task{System.}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Completeness.Activities.GetAllOrchestratorsActivity.RunAsync(Microsoft.Azure.WebJobs.DurableActivityContextBase,Microsoft.Azure.WebJobs.DurableOrchestrationClientBase)~System.Threading.Tasks.Task{System.}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Completeness.Activities.GetAllOrchestratorsActivity.RunAsync(Microsoft.Azure.WebJobs.DurableActivityContextBase,Microsoft.Azure.WebJobs.DurableOrchestrationClientBase)~System.Threading.Tasks.Task{System.}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Completeness.Activities.GetAllOrchestratorsActivity.RunAsync(Microsoft.Azure.WebJobs.DurableActivityContextBase,Microsoft.Azure.WebJobs.DurableOrchestrationClientBase)~System.Threading.Tasks.Task{System.}")]

