
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Blocker Code Smell", "S2699:Tests should include assertions", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Tests.Activities.GetScannedSupervisorsActivityTests.ShouldQueryLogAnalytics~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Blocker Code Smell", "S2699:Tests should include assertions", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Tests.Activities.PurgeMultipleOrchestratorsActivityTests.ShouldSendDeleteCall~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Blocker Code Smell", "S2699:Tests should include assertions", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Tests.Activities.PurgeSingleOrchestratorActivityTests.ShouldSendDeleteCall~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Blocker Code Smell", "S2699:Tests should include assertions", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Tests.Activities.TerminateOrchestratorActivityTests.ShouldSendTerminateCall~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Blocker Code Smell", "S2699:Tests should include assertions", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Tests.Activities.UploadCompletenessLogsActivityTests.ShouldUploadToLogAnalytics~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Blocker Code Smell", "S2699:Tests should include assertions", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Tests.Orchestrators.CompletenessOrchestratorTests.ShouldStartActivitiesForGettingOrchestratorsToAnalyze~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Blocker Code Smell", "S2699:Tests should include assertions", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Tests.Orchestrators.CompletenessOrchestratorTests.ShouldStartDeleteActivityForEachCompletedSupervisor(System.Int32)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Blocker Code Smell", "S2699:Tests should include assertions", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Tests.Orchestrators.CompletenessOrchestratorTests.ShouldStartSubOrchestratorForEachAnalysis(System.Int32)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Blocker Code Smell", "S2699:Tests should include assertions", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Tests.Orchestrators.OrchestratorCleanUpOrchestratorTests.ShouldStartActivities~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Blocker Code Smell", "S2699:Tests should include assertions", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Tests.Orchestrators.OrchestratorCleanUpOrchestratorTests.ShouldStartDeleteActivityForEachOrchestrator(System.Int32)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Blocker Code Smell", "S2699:Tests should include assertions", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Tests.Orchestrators.SingleCompletenessOrchestratorTests.ShouldCallActivities~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Blocker Code Smell", "S2699:Tests should include assertions", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Tests.Orchestrators.SingleCompletenessOrchestratorTests.ShouldStartDeleteActivityForEachCompletedOrchestrator(System.Int32)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Blocker Code Smell", "S2699:Tests should include assertions", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Tests.PoisonQueueTests.SkipIfQueueNameIsEmpty~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Blocker Code Smell", "S2699:Tests should include assertions", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Tests.Starters.CompletenessStarterTests.ShouldStartOrchestrator~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Blocker Code Smell", "S2699:Tests should include assertions", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Tests.Starters.OrchestratorCleanUpStarterTests.ShouldStartOrchestrator~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Blocker Code Smell", "S2699:Tests should include assertions", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Tests.StartupTests.TestDependencyInjectionResolve")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Blocker Code Smell", "S2699:Tests should include assertions", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Tests.Orchestrators.ImpactAnalysisOrchestratorTests.ShouldStartActivities(System.Int32)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Blocker Code Smell", "S2699:Tests should include assertions", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Tests.Starters.ImpactAnalysisStarterTests.ShouldStartOrchestrator~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Blocker Code Smell", "S2699:Tests should include assertions", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Tests.Activities.UploadReleaseLogActivityTests.ShouldUploadToLogAnalytics~System.Threading.Tasks.Task")]