
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Blocker Code Smell", "S2699:Tests should include assertions", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Tests.PoisonQueueTests.SkipIfQueueNameIsEmpty~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Blocker Code Smell", "S2699:Tests should include assertions", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Tests.StartupTests.TestDependencyInjectionResolve")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Blocker Code Smell", "S2699:Tests should include assertions", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Tests.Completeness.Activities.GetCompletedScansFromLogAnalyticsActivityTests.ShouldQueryLogAnalytics~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Blocker Code Smell", "S2699:Tests should include assertions", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Tests.Completeness.Activities.UploadAnalysisResultToLogAnalyticsActivityTests.ShouldUploadToLogAnalytics~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Blocker Code Smell", "S2699:Tests should include assertions", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Tests.Completeness.Orchestrators.CompletenessCheckOrchestratorTests.ShouldStartActivitiesForGettingOrchestratorsToAnalyze~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Blocker Code Smell", "S2699:Tests should include assertions", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Tests.Completeness.Orchestrators.CompletenessCheckOrchestratorTests.ShouldStartSubOrchestratorForEachAnalysis(System.Int32)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Blocker Code Smell", "S2699:Tests should include assertions", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Tests.Completeness.Orchestrators.SingleAnalysisOrchestratorTests.ShouldCallActivities~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Blocker Code Smell", "S2699:Tests should include assertions", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Tests.Completeness.Orchestrators.SingleAnalysisOrchestratorTests.ShouldNotAnalyzeIfNoTotalProjectCount~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Blocker Code Smell", "S2699:Tests should include assertions", Justification = "<Pending>", Scope = "member", Target = "~M:Functions.Tests.Completeness.Starters.CompletenessCheckStarterTests.ShouldStartOrchestrator~System.Threading.Tasks.Task")]