
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S1450:Private fields only used as local variables in methods should become local variables", Justification = "<Pending>", Scope = "member", Target = "~F:CompletenessCheckFunction.Activities.GetCompletedScansFromLogAnalyticsActivity._client")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S1450:Private fields only used as local variables in methods should become local variables", Justification = "<Pending>", Scope = "member", Target = "~F:CompletenessCheckFunction.Activities.UploadAnalysisResultToLogAnalyticsActivity._client")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0052:Remove unread private members", Justification = "<Pending>", Scope = "member", Target = "~F:CompletenessCheckFunction.Activities.GetCompletedScansFromLogAnalyticsActivity._client")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0052:Remove unread private members", Justification = "<Pending>", Scope = "member", Target = "~F:CompletenessCheckFunction.Activities.UploadAnalysisResultToLogAnalyticsActivity._client")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S103:Lines should not be too long", Justification = "<Pending>")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:CompletenessCheckFunction.Activities.GetCompletedScansFromLogAnalyticsActivity.Run(Microsoft.Azure.WebJobs.DurableOrchestrationContextBase)~System.Collections.Generic.IList{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:CompletenessCheckFunction.Starters.CompletenessCheckStarter.RunAsync(Microsoft.Azure.WebJobs.TimerInfo,Microsoft.Azure.WebJobs.DurableOrchestrationClientBase)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S4004:Collection properties should be readonly", Justification = "<Pending>", Scope = "member", Target = "~P:CompletenessCheckFunction.Requests.FilterAlreadyAnalyzedOrchestratorsActivityRequest.InstanceIdsAlreadyAnalyzed")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S4004:Collection properties should be readonly", Justification = "<Pending>", Scope = "member", Target = "~P:CompletenessCheckFunction.Requests.FilterAlreadyAnalyzedOrchestratorsActivityRequest.InstancesToAnalyze")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S4004:Collection properties should be readonly", Justification = "<Pending>", Scope = "member", Target = "~P:CompletenessCheckFunction.Requests.FilterOrchestratorsForParentIdActivityRequest.InstancesToFilter")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S4004:Collection properties should be readonly", Justification = "<Pending>", Scope = "member", Target = "~P:CompletenessCheckFunction.Requests.SingleAnalysisOrchestratorRequest.AllProjectScanOrchestrators")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Critical Code Smell", "S3216:\"ConfigureAwait(false)\" should be used", Justification = "<Pending>", Scope = "member", Target = "~M:CompletenessCheckFunction.Orchestrators.SingleAnalysisOrchestrator.RunInternalAsync(Microsoft.Azure.WebJobs.DurableOrchestrationContextBase)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Critical Code Smell", "S3216:\"ConfigureAwait(false)\" should be used", Justification = "<Pending>", Scope = "member", Target = "~M:CompletenessCheckFunction.Orchestrators.CompletenessCheckOrchestrator.RunAsync(Microsoft.Azure.WebJobs.DurableOrchestrationContextBase)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:CompletenessCheckFunction.Activities.GetCompletedScansFromLogAnalyticsActivity.RunAsync(Microsoft.Azure.WebJobs.DurableActivityContextBase)~System.Threading.Tasks.Task{LogAnalytics.Client.Response.LogAnalyticsQueryResponse}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:CompletenessCheckFunction.Activities.GetCompletedScansFromLogAnalyticsActivity.RunAsync(Microsoft.Azure.WebJobs.DurableActivityContextBase)~System.Threading.Tasks.Task{System.Collections.Generic.List{System.String}}")]