pool:
  name: Rabo-Build-Azure-Linux-Preview

steps:
  - task: DotNetCoreInstaller@0
    displayName: 'Use .NET Core sdk 2.2.203'
    inputs:
      version: 2.2.203
    enabled: false

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      vstsFeed: 'ea1adc59-f67e-40d5-8539-4c897a894647'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      arguments: '--configuration release'

  - script: docker run --name azurite -d -p 10001:10001 arafato/azurite
    displayName: docker run azurite
      
  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      arguments: '--configuration release'

  - script: docker rm -f azurite
    displayName: docker rm azurite
    condition: always()

  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: false
      arguments: '--configuration release --output $(build.artifactstagingdirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      ArtifactName: 'vsts-webhook-function'

