name: test
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100'
          source-url: https://nuget.pkg.github.com/azure-devops-compliance/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: dotnet build -c release
  test:
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100'
          source-url: https://nuget.pkg.github.com/azure-devops-compliance/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: dotnet test
        run: dotnet test -c release  /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
        env:
          TOKEN: ${{secrets.AZURE_DEVOPS_TOKEN}}
          AzureWebJobsStorage: ${{secrets.AzureWebJobsStorage}}
      - uses: codecov/codecov-action@v1
  mutation-test:
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100'
          source-url: https://nuget.pkg.github.com/azure-devops-compliance/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: stryker
        run: |
          dotnet tool install -g dotnet-stryker
          dotnet stryker -tp "['Functions.Tests/Functions.Tests.csproj']" -im "['ConfigureAwait']" --reporters "['dashboard']" --dashboard-project github.com/azure-devops-compliance/azure-functions/master
        env:
          STRYKER_DASHBOARD_API_KEY: ${{secrets.STRYKER_DASHBOARD_TOKEN}}